# docker-compose version
version: "3.3"

services:
  # images
mysql-dev:
  image: mysql:5.7
  environment:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: test_db
  ports:
    - "3306:3306"
  # making data persistent
  volumes:
    - db-data:/var/lib/mysql

volumes:
db-data:
