name: ShellCheck

on:
  push:
    branches:
      - main 

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install ShellCheck
      run: |
        sudo apt-get update
        sudo apt-get install shellcheck -y

    - name: Run ShellCheck
      run: shellcheck *.sh
