name: shellcheck

on:
  push:
    branches:
      - main

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache shellcheck
      id: cache-shellcheck
      uses: actions/cache@v1
      with:
        path: ~/.local/bin/shellcheck
        key: ${{ runner.os }}-shellcheck

    - name: Install shellcheck
      if: steps.cache-shellcheck.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install shellcheck -y

    - name: Run ShellCheck
      run: shellcheck *.sh
